spring:
  application:
    name: user
  data:
    neo4j:
      uri: http://10.211.55.3:7474
      username: neo4j
      password: xiaoqian666
  datasource:
    url: jdbc:mysql://localhost:3306/cmd_vs?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xiaoqian666
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 10.211.55.3
    port: 6379
  servlet:
    # 文件上传
    multipart:
      # 单个上传文件的最大允许大小
      max-file-size: 1MB
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 1MB

server:
  port: 8081

logging:
  level:
    com.xiaoqian: debug
